// Maps freeform country names (as typed by vendors in project_country / customers
// in nationality fields) to ISO 3166-1 alpha-2 codes, for flag lookups via flagcdn.com.
// Vendors type these by hand, so this covers common spellings/aliases, not just
// official names.
const COUNTRY_TO_ISO2: Record<string, string> = {
  singapore: "sg",
  malaysia: "my",
  indonesia: "id",
  brunei: "bn",
  thailand: "th",
  philippines: "ph",
  vietnam: "vn",
  cambodia: "kh",
  laos: "la",
  myanmar: "mm",
  burma: "mm",
  "sri lanka": "lk",
  india: "in",
  pakistan: "pk",
  bangladesh: "bd",
  nepal: "np",
  afghanistan: "af",
  china: "cn",
  japan: "jp",
  "south korea": "kr",
  korea: "kr",
  yemen: "ye",
  "saudi arabia": "sa",
  saudi: "sa",
  uae: "ae",
  "united arab emirates": "ae",
  qatar: "qa",
  kuwait: "kw",
  bahrain: "bh",
  oman: "om",
  jordan: "jo",
  lebanon: "lb",
  syria: "sy",
  iraq: "iq",
  iran: "ir",
  palestine: "ps",
  turkey: "tr",
  turkiye: "tr",
  egypt: "eg",
  libya: "ly",
  tunisia: "tn",
  algeria: "dz",
  morocco: "ma",
  sudan: "sd",
  "south sudan": "ss",
  somalia: "so",
  djibouti: "dj",
  ethiopia: "et",
  eritrea: "er",
  kenya: "ke",
  tanzania: "tz",
  uganda: "ug",
  rwanda: "rw",
  burundi: "bi",
  malawi: "mw",
  mozambique: "mz",
  zambia: "zm",
  zimbabwe: "zw",
  "south africa": "za",
  nigeria: "ng",
  niger: "ne",
  chad: "td",
  mali: "ml",
  senegal: "sn",
  gambia: "gm",
  "sierra leone": "sl",
  liberia: "lr",
  "ivory coast": "ci",
  "cote d'ivoire": "ci",
  ghana: "gh",
  togo: "tg",
  benin: "bj",
  cameroon: "cm",
  gabon: "ga",
  mauritania: "mr",
  comoros: "km",
  maldives: "mv",
  kazakhstan: "kz",
  uzbekistan: "uz",
  tajikistan: "tj",
  kyrgyzstan: "kg",
  turkmenistan: "tm",
  azerbaijan: "az",
  albania: "al",
  bosnia: "ba",
  "bosnia and herzegovina": "ba",
  kosovo: "xk",
  "united kingdom": "gb",
  uk: "gb",
  england: "gb",
  "united states": "us",
  usa: "us",
  america: "us",
  australia: "au",
  canada: "ca",
  france: "fr",
  germany: "de",
  netherlands: "nl",
};

export function countryNameToIso2(name: string | null | undefined): string | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  if (COUNTRY_TO_ISO2[key]) return COUNTRY_TO_ISO2[key];
  const match = Object.entries(COUNTRY_TO_ISO2).find(([label]) => key.includes(label) || label.includes(key));
  return match ? match[1] : null;
}

export function flagUrl(iso2: string | null): string | null {
  if (!iso2) return null;
  return `https://flagcdn.com/w320/${iso2}.png`;
}
